# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import stanza_pb2 as stanza__pb2


class StanzaStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Recognize = channel.unary_unary(
                '/stanza.grpc.v1.Stanza/Recognize',
                request_serializer=stanza__pb2.RecognizeRequest.SerializeToString,
                response_deserializer=stanza__pb2.RecognizeResponse.FromString,
                )


class StanzaServicer(object):
    """Missing associated documentation comment in .proto file"""

    def Recognize(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StanzaServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Recognize': grpc.unary_unary_rpc_method_handler(
                    servicer.Recognize,
                    request_deserializer=stanza__pb2.RecognizeRequest.FromString,
                    response_serializer=stanza__pb2.RecognizeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'stanza.grpc.v1.Stanza', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Stanza(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def Recognize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stanza.grpc.v1.Stanza/Recognize',
            stanza__pb2.RecognizeRequest.SerializeToString,
            stanza__pb2.RecognizeResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
