# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stanza.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='stanza.proto',
  package='stanza.grpc.v1',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0cstanza.proto\x12\x0estanza.grpc.v1\x1a\x1cgoogle/api/annotations.proto\"$\n\x10RecognizeRequest\x12\x10\n\x08sentence\x18\x01 \x01(\t\".\n\x11RecognizeResponse\x12\x19\n\x11recognized_result\x18\x01 \x01(\t2t\n\x06Stanza\x12j\n\tRecognize\x12 .stanza.grpc.v1.RecognizeRequest\x1a!.stanza.grpc.v1.RecognizeResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\r/v1/recognize:\x01*b\x06proto3'
  ,
  dependencies=[google_dot_api_dot_annotations__pb2.DESCRIPTOR,])




_RECOGNIZEREQUEST = _descriptor.Descriptor(
  name='RecognizeRequest',
  full_name='stanza.grpc.v1.RecognizeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sentence', full_name='stanza.grpc.v1.RecognizeRequest.sentence', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=98,
)


_RECOGNIZERESPONSE = _descriptor.Descriptor(
  name='RecognizeResponse',
  full_name='stanza.grpc.v1.RecognizeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='recognized_result', full_name='stanza.grpc.v1.RecognizeResponse.recognized_result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=100,
  serialized_end=146,
)

DESCRIPTOR.message_types_by_name['RecognizeRequest'] = _RECOGNIZEREQUEST
DESCRIPTOR.message_types_by_name['RecognizeResponse'] = _RECOGNIZERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RecognizeRequest = _reflection.GeneratedProtocolMessageType('RecognizeRequest', (_message.Message,), {
  'DESCRIPTOR' : _RECOGNIZEREQUEST,
  '__module__' : 'stanza_pb2'
  # @@protoc_insertion_point(class_scope:stanza.grpc.v1.RecognizeRequest)
  })
_sym_db.RegisterMessage(RecognizeRequest)

RecognizeResponse = _reflection.GeneratedProtocolMessageType('RecognizeResponse', (_message.Message,), {
  'DESCRIPTOR' : _RECOGNIZERESPONSE,
  '__module__' : 'stanza_pb2'
  # @@protoc_insertion_point(class_scope:stanza.grpc.v1.RecognizeResponse)
  })
_sym_db.RegisterMessage(RecognizeResponse)



_STANZA = _descriptor.ServiceDescriptor(
  name='Stanza',
  full_name='stanza.grpc.v1.Stanza',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=148,
  serialized_end=264,
  methods=[
  _descriptor.MethodDescriptor(
    name='Recognize',
    full_name='stanza.grpc.v1.Stanza.Recognize',
    index=0,
    containing_service=None,
    input_type=_RECOGNIZEREQUEST,
    output_type=_RECOGNIZERESPONSE,
    serialized_options=b'\202\323\344\223\002\022\022\r/v1/recognize:\001*',
  ),
])
_sym_db.RegisterServiceDescriptor(_STANZA)

DESCRIPTOR.services_by_name['Stanza'] = _STANZA

# @@protoc_insertion_point(module_scope)
