# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stanza.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='stanza.proto',
  package='stanza.grpc.v1',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0cstanza.proto\x12\x0estanza.grpc.v1\x1a\x1cgoogle/api/annotations.proto\",\n\x18RecognizeSentenceRequest\x12\x10\n\x08sentence\x18\x01 \x01(\t\"H\n\x19RecognizeSentenceResponse\x12\x10\n\x08sentence\x18\x01 \x01(\t\x12\x19\n\x11recognized_result\x18\x02 \x01(\t2\x8d\x01\n\x06Stanza\x12\x82\x01\n\x11RecognizeSentence\x12(.stanza.grpc.v1.RecognizeSentenceRequest\x1a).stanza.grpc.v1.RecognizeSentenceResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\r/v1/recognize:\x01*b\x06proto3'
  ,
  dependencies=[google_dot_api_dot_annotations__pb2.DESCRIPTOR,])




_RECOGNIZESENTENCEREQUEST = _descriptor.Descriptor(
  name='RecognizeSentenceRequest',
  full_name='stanza.grpc.v1.RecognizeSentenceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sentence', full_name='stanza.grpc.v1.RecognizeSentenceRequest.sentence', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=106,
)


_RECOGNIZESENTENCERESPONSE = _descriptor.Descriptor(
  name='RecognizeSentenceResponse',
  full_name='stanza.grpc.v1.RecognizeSentenceResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sentence', full_name='stanza.grpc.v1.RecognizeSentenceResponse.sentence', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='recognized_result', full_name='stanza.grpc.v1.RecognizeSentenceResponse.recognized_result', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=108,
  serialized_end=180,
)

DESCRIPTOR.message_types_by_name['RecognizeSentenceRequest'] = _RECOGNIZESENTENCEREQUEST
DESCRIPTOR.message_types_by_name['RecognizeSentenceResponse'] = _RECOGNIZESENTENCERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RecognizeSentenceRequest = _reflection.GeneratedProtocolMessageType('RecognizeSentenceRequest', (_message.Message,), {
  'DESCRIPTOR' : _RECOGNIZESENTENCEREQUEST,
  '__module__' : 'stanza_pb2'
  # @@protoc_insertion_point(class_scope:stanza.grpc.v1.RecognizeSentenceRequest)
  })
_sym_db.RegisterMessage(RecognizeSentenceRequest)

RecognizeSentenceResponse = _reflection.GeneratedProtocolMessageType('RecognizeSentenceResponse', (_message.Message,), {
  'DESCRIPTOR' : _RECOGNIZESENTENCERESPONSE,
  '__module__' : 'stanza_pb2'
  # @@protoc_insertion_point(class_scope:stanza.grpc.v1.RecognizeSentenceResponse)
  })
_sym_db.RegisterMessage(RecognizeSentenceResponse)



_STANZA = _descriptor.ServiceDescriptor(
  name='Stanza',
  full_name='stanza.grpc.v1.Stanza',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=183,
  serialized_end=324,
  methods=[
  _descriptor.MethodDescriptor(
    name='RecognizeSentence',
    full_name='stanza.grpc.v1.Stanza.RecognizeSentence',
    index=0,
    containing_service=None,
    input_type=_RECOGNIZESENTENCEREQUEST,
    output_type=_RECOGNIZESENTENCERESPONSE,
    serialized_options=b'\202\323\344\223\002\022\022\r/v1/recognize:\001*',
  ),
])
_sym_db.RegisterServiceDescriptor(_STANZA)

DESCRIPTOR.services_by_name['Stanza'] = _STANZA

# @@protoc_insertion_point(module_scope)
